spring.application.name=banking-system

spring.datasource.url=jdbc:mysql://localhost:3306/banking_system
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true